#!/usr/bin/env bash

header_info() {
  clear
  cat <<"EOF"

pve 8 to 9 upgrade

EOF
}

RD=$(echo "\033[01;31m")
YW=$(echo "\033[33m")
GN=$(echo "\033[1;92m")
CL=$(echo "\033[m")
BFR="\\r\\033[K"
HOLD="-"
CM="${GN}✓${CL}"
CROSS="${RD}✗${CL}"

set -euo pipefail
shopt -s inherit_errexit nullglob

msg_info() {
  local msg="$1"
  echo -ne " ${HOLD} ${YW}${msg}..."
}

msg_ok() {
  local msg="$1"
  echo -e "${BFR} ${CM} ${GN}${msg}${CL}"
}

msg_error() {
  local msg="$1"
  echo -e "${BFR} ${CROSS} ${RD}${msg}${CL}"
}

start_routines() {
  header_info

  whiptail --backtitle "Proxmox VE Upgrade" --msgbox --title "PVE9 SOURCES" "This will set the correct sources to update and install Proxmox VE 9." 10 58
    msg_info "Changing to Proxmox VE 9 Sources"
    cat <<EOF >/etc/apt/sources.list
deb http://ftp.debian.org/debian trixie main contrib
deb http://ftp.debian.org/debian trixie-updates main contrib
deb http://security.debian.org/debian-security trixie-security main contrib
EOF
    msg_ok "Changed to Proxmox VE 9 Sources"

  whiptail --backtitle "Proxmox VE Upgrade" --msgbox --title "PVE9-ENTERPRISE" "The 'pve-enterprise' repository is only available to users who have purchased a Proxmox VE subscription." 10 58
    msg_info "Disabling 'pve-enterprise' repository"
    cat <<EOF >/etc/apt/sources.list.d/pve-enterprise.list
# deb https://enterprise.proxmox.com/debian/pve trixie pve-enterprise
EOF
    msg_ok "Disabled 'pve-enterprise' repository"

  whiptail --backtitle "Proxmox VE Upgrade" --msgbox --title "PVE9-NO-SUBSCRIPTION" "The 'pve-no-subscription' repository provides access to all of the open-source components of Proxmox VE." 10 58
    msg_info "Enabling 'pve-no-subscription' repository"
    cat <<EOF >/etc/apt/sources.list.d/pve-install-repo.list
deb http://download.proxmox.com/debian/pve trixie pve-no-subscription
EOF
    msg_ok "Enabled 'pve-no-subscription' repository"

  whiptail --backtitle "Proxmox VE Upgrade" --msgbox --title "PVE9 CEPH PACKAGE REPOSITORIES" "The 'Ceph Package Repositories' provides access to both the 'no-subscription' and 'enterprise' repositories." 10 58
    msg_info "Enabling 'ceph package repositories'"
    cat <<EOF >/etc/apt/sources.list.d/ceph.list
# deb https://enterprise.proxmox.com/debian/ceph-quincy trixie enterprise
deb http://download.proxmox.com/debian/ceph-quincy trixie no-subscription
EOF
    msg_ok "Enabled 'ceph package repositories'"

  whiptail --backtitle "Proxmox VE Upgrade" --msgbox --title "PVE9 TEST" "The 'pvetest' repository can give advanced users access to new features and updates before they are officially released (Disabled)." 10 58
    msg_info "Adding 'pvetest' repository and set disabled"
    cat <<EOF >/etc/apt/sources.list.d/pvetest-for-beta.list
# deb http://download.proxmox.com/debian/pve trixie pvetest
EOF
    msg_ok "Added 'pvetest' repository"

  whiptail --backtitle "Proxmox VE Upgrade" --msgbox --title "PVE9 UPDATE" "Updating to Proxmox VE 9" 10 58
    msg_info "Updating to Proxmox VE 9 (Patience)"
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" dist-upgrade -y
    msg_ok "Updated to Proxmox VE 9"

  CHOICE=$(whiptail --backtitle "Proxmox VE Upgrade" --title "REBOOT" --menu "\nReboot Proxmox VE 9 now? (recommended)" 11 58 2 \
    "yes" " " \
    "no" " " 3>&2 2>&1 1>&3)
  case $CHOICE in
  yes)
    msg_info "Rebooting Proxmox VE 9"
    sleep 2
    msg_ok "Completed Install Routines"
    reboot
    ;;
  no)
    msg_error "Selected no to Rebooting Proxmox VE 9 (Reboot recommended)"
    msg_ok "Completed Install Routines"
    ;;
  esac
}

header_info
while true; do
  read -p "Start the Update to Proxmox VE 9 Script (y/n)?" yn
  case $yn in
  [Yy]*) break ;;
  [Nn]*) clear; exit ;;
  *) echo "Please answer yes or no." ;;
  esac
done

if ! command -v pveversion >/dev/null 2>&1; then
  header_info
  msg_error "\n No PVE Detected!\n"
  exit
fi

if ! pveversion | grep -Eq "pve-manager/(8\.4-(16|17|18|19))"; then
  header_info
  msg_error "This version of Proxmox Virtual Environment is not supported"
  echo -e "  PVE Version 8.4-16 or higher is required."
  echo -e "\nExiting..."
  sleep 3
  exit
fi

start_routines
